# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "helm" {
  kubernetes = {
    host                   = var.eks_cluster_endpoint
    cluster_ca_certificate = base64decode(var.cluster_ca_data)
    exec = {
      api_version = "client.authentication.k8s.io/v1beta1"
      args        = ["eks", "get-token", "--cluster-name", var.eks_full_name]
      command     = "aws"
    }
  }
}
